name: AutoSync
on:
  workflow_dispatch:

jobs:
  Sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download File
        run: |
          latest_version=$(wget -qO- -t1 -T2 "https://api.github.com/repos/ZyCromerZ/Clang/releases/latest" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g')
          file_name="Clang-"${latest_version%????????}".tar.gz"
          echo $latest_version
          echo $file_name
          wget https://github.com/ZyCromerZ/Clang/releases/download/$latest_version/$file_name
          ls
      - name: Extract File & Clean
        run: |
          latest_version=$(wget -qO- -t1 -T2 "https://api.github.com/repos/ZyCromerZ/Clang/releases/latest" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g')
          file_name="Clang-"${latest_version%????????}".tar.gz"
          tar -zxvf $file_name
          rm -rf $file_name
          ls
      - name: Upload Files
        run: |
          lfs_latest_version=$(wget -qO- -t1 -T2 "https://api.github.com/repos/git-lfs/git-lfs/releases/latest" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g')
          lfs_file_name="git-lfs-linux-amd64-"$lfs_latest_version".tar.gz"
          version_code_without_v=${lfs_latest_version: 1}
          dir_name="git-lfs-"$version_code_without_v
          wget https://github.com/git-lfs/git-lfs/releases/download/$lfs_latest_version/$lfs_file_name
          tar -zxvf $lfs_file_name
          cd $dir_name
          chmod +x install.sh
          sudo ./install.sh
          git lfs install
          cd ..
          rm -rf $dir_name
          rm -rf $lfs_file_name
          sudo git config user.name 'magojohnji'
          sudo git config user.email 'magojohnji@users.noreply.github.com'
          sudo git lfs track "./lib/libclang-cpp.so.18git"
          sudo git add .gitattributes
          sudo git add .
          sudo git commit -m "$(date "+%Y-%m-%d %H:%M:%S") UTC" -a
          sudo git push


