name: AutoSync
on:
  workflow_dispatch:

jobs:
  Sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download File
        run: |
          latest_version=$(wget -qO- -t1 -T2 "https://api.github.com/repos/ZyCromerZ/Clang/releases/latest" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g')
          file_name="Clang-"${latest_version%????????}".tar.gz"
          wget https://github.com/ZyCromerZ/Clang/releases/download/$latest_version/$file_name
      - name: Extract File & Clean
        run: |
          tar -zxvf $file_name
          rm -rf $file_name
      - name: Upload Files
        run: |
          {
              git config user.name github-actions
              git config user.email github-actions@github.com
              git add .
              git commit -m "$(date "+%Y-%m-%d %H:%M:%S") UTC" -a
              if [ $? -eq 0 ]; then
                  git commit -m "$(date "+%Y-%m-%d %H:%M:%S") UTC" -a
                  git push
              else
                  echo No Update
              fi
          } || {
              echo Execution Failed
              exit 1
          }

